language: c
env:
    global: DISPLAY=:99.0

jobs:
  include:
    - os: osx
      python: "Macos Python 3.8"
      env: CONDA_PYTHON="3.8" CONDA_OS="MacOSX" KMP_DUPLICATE_LIB_OK=TRUE CC=g++ CXX=g++ DOWNLOAD_MNE_DATA=FALSE
    - os: linux
      name: "Linux Python 3.9"
      env: CONDA_PYTHON="3.8" CONDA_OS="Linux"
      addons: {apt: {packages: [libwebkitgtk-dev]}}

# Setup anaconda
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
       /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
    fi;
  - wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$CONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  # Useful for debugging any issues with conda
  - mamba info -a
  - mamba create -y -q -n condaenv python=$CONDA_PYTHON
  - mamba env update -q -n condaenv --file env-dev.yml --prune
  - conda activate condaenv
  - python --version

install:
  - python -m pip install -e .

script:
  - travis_wait pytest
